#' Append filtering results to input vcf file
#'
#' @param vcf_filename input vcf
#' @param predictions predictions generated by filter_variants
#'
#' @return
#' @export
#'
#' @examples
write_vcf <- function(vcf_filename, predictions, outname) {
  # Write predictions to a temporary tab-delimited file
  tmpdir <- "/tmp"
  tmp_filename <- file.path(tmpdir, "ideafix_preds.temp")
  write.table(predictions, file = tmp_filename, sep = "\t", row.names = FALSE, quote = FALSE)
  # Write header tags
  header_text <- '##INFO=<ID=DEAM_SCORE,Number=1,Type=Float,Description="Deamination score of the variant.">\n##INFO=<ID=DEAMINATION,Number=1,Type=String,Description="Classification of the variant as deamination or non-deamination.">'
  hdr_filename <- file.path(tmpdir, "ideafix_preds.hdr")
  writeLines(header_text, con = hdr_filename)
  # Compress and index the file
  compress_cmd <- sprintf("tail -n +2 %s | bgzip -c > %s.gz", tmp_filename, tmp_filename)
  system(compress_cmd, intern = FALSE)
  idx_cmd <- sprintf("tabix -p vcf %s.gz", tmp_filename)
  system(idx_cmd, intern = FALSE)
  # Annotate the vcf file
  annotate_cmd <- sprintf("bcftools annotate -a %s.gz -h %s -c CHROM,POS,REF,ALT,DEAM_SCORE,DEAMINATION -o %s.vcf %s", tmp_filename, hdr_filename, outname, vcf_filename)
  system(annotate_cmd, intern = FALSE)
}

#' Annotate deaminations
#'
#' Exports prediction results to a text file
#'
#' @param predictions predictions generated by filter_variants
#' @param format exported file format. Can be "tsv" or "vcf". Defaults to "tsv".
#' @param outfolder folder to output the exported file. Defaults to current working directory
#' @param outname filename of exported file. Defaults to "ideafix_labels.txt"
#' @param vcf_filename if format is "vcf", path to the vcf file ideafix has been run over
#'
#' @return None
#' @export
#' @details In case vcf is selected, the vcf must be provided the results will be appended to input vcf file...
#'
#' @examples
annotate_deaminations <- function(predictions, format = "tsv", outfolder = ".", outname = "ideafix_labels", vcf_filename = NULL) {
  if (format == "tsv") {
    write.table(predictions, file = file.path(outfolder, sprintf("%s.txt", outname)), sep = "\t", row.names = FALSE, quote = FALSE)
  }
  else if (format == "vcf") {
    if (is.null(vcf_filename)) {
      stop("Path to the vcf file ideafix has been run over must be provided.")
    } else {
      write_vcf(vcf_filename = vcf_filename, predictions = predictions, outname = file.path(outfolder, outname))
    }
  } else {
    warning("Export file format not recognized. Results will be exported to tsv file.")
    write.table(predictions, file = file.path(outfolder, sprintf("%s.txt", outname)), sep = "\t", row.names = FALSE, quote = FALSE)
  }
}


