#' Title
#'
#' @param vcf_filename input vcf
#' @param predictions predictions generated by filter_variants
#'
#' @return
#' @export
#'
#' @examples
append_vcf <- function(vcf_filename, predictions) {
  # Write predictions to a temporary tab-delimited file

  # Annotate the vcf from the file
  system("tabix -s1 -b2 -e2 annots.tab.gz")
  system("bcftools annotate -a annots.tab.gz -h annots.hdr -c CHROM,POS,REF,ALT,-,TAG file.vcf")
}
